packages:
  - .
overrides:
  miniflare>sharp: 0.35.4
minimumReleaseAge: 0
trustLockfile: true
strictDepBuilds: true
allowBuilds:
  esbuild: true
  fsevents: true
  sharp: true
  unrs-resolver: true
  workerd: true
