"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
type Entry={id:string;name:string;status:string;role:string;createdAt:number};
export default function AdminPage(){
 const [rows,setRows]=useState<Entry[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 const [target,setTarget]=useState<Entry|null>(null),[password,setPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[visible,setVisible]=useState(false);
 const reload=useCallback(async()=>{try{const response=await fetch("/api/admin/accounts",{cache:"no-store"});const result=await response.json() as {error?:string;accounts?:Entry[]};if(!response.ok)throw Error(result.error||"无法读取账号");setRows(result.accounts||[]);setError("");}catch(e){setError(e instanceof Error?e.message:"无法读取账号");}},[]);
 useEffect(()=>{void reload();},[reload]);
 async function decide(id:string,status:"approved"|"rejected"){setBusy(id);setError("");try{const response=await fetch("/api/admin/accounts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const result=await response.json() as {error?:string;accounts?:Entry[]};if(!response.ok)throw Error(result.error||"操作失败");await reload();}catch(e){setError(e instanceof Error?e.message:"操作失败");}finally{setBusy("");}}
 async function reset(event:FormEvent){event.preventDefault();if(!target)return;if(password!==confirmation){setError("两次输入的新密码不一致");return;}setBusy(target.id);setError("");try{const response=await fetch("/api/admin/accounts/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:target.id,newPassword:password})});const result=await response.json() as {error?:string;accounts?:Entry[]};if(!response.ok)throw Error(result.error||"修改失败");setMessage(`${target.name} 的密码已重设，请通知该同事使用新密码重新登录。`);setTarget(null);setPassword("");setConfirmation("");}catch(e){setError(e instanceof Error?e.message:"修改失败");}finally{setBusy("");}}
 const button="rounded border px-3 py-2 text-sm disabled:opacity-50";
 return <main className="mx-auto max-w-4xl px-4 py-8 text-slate-800"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">管理员 · 账号管理</h1><a href="/sheet-test" className="text-blue-700 underline">返回 Excel 模式</a></div><div className="my-4 flex flex-wrap gap-3"><a className={button} href="/admin/data">全部业务数据</a><a className={button} href="/haulier-stats">全部车队统计</a><a className={button} href="/quotes">全部报价</a><a className={button} href="/account">修改管理员密码</a></div><p className="text-sm text-slate-500">新账号需批准后登录。重设密码会使该账号原有登录失效，业务资料保留。</p>{error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{message&&<p role="status" className="mt-3 text-green-700">{message}</p>}<div className="mt-5 space-y-3">{rows.map(row=><section key={row.id} className="flex flex-wrap items-center gap-3 rounded-lg border bg-white p-4"><div className="min-w-40 flex-1"><strong>{row.name}</strong><p className="text-sm text-slate-500">{row.role==="admin"?"管理员":row.status==="pending"?"待批准":row.status==="approved"?"已批准":"已拒绝"} · {new Date(row.createdAt).toLocaleString("zh-CN",{timeZone:"Asia/Kuala_Lumpur"})}</p></div><a className={button} href={`/admin/data?owner=${encodeURIComponent(row.id)}`}>查看数据</a>{row.role!=="admin"&&<button disabled={!!busy} className={button} onClick={()=>{setTarget(row);setPassword("");setConfirmation("");setVisible(false);setError("");setMessage("");}}>重设密码</button>}{row.role!=="admin"&&["pending","rejected"].includes(row.status)&&<><button disabled={!!busy} className={`${button} bg-teal-700 text-white`} onClick={()=>void decide(row.id,"approved")}>批准</button>{row.status==="pending"&&<button disabled={!!busy} className={button} onClick={()=>void decide(row.id,"rejected")}>拒绝</button>}</>}</section>)}{!rows.length&&!error&&<p>暂无账号。</p>}</div>
 {target&&<div className="fixed inset-0 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="重设账号密码" onSubmit={reset} className="w-full max-w-md rounded-xl bg-white p-5"><h2 className="font-semibold">重设密码 · {target.name}</h2><label className="mt-4 block text-sm">新密码<input required minLength={12} maxLength={128} autoComplete="new-password" type={visible?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 h-10 w-full rounded border px-2"/></label><label className="mt-3 block text-sm">确认新密码<input required minLength={12} maxLength={128} autoComplete="new-password" type={visible?"text":"password"} value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="mt-1 h-10 w-full rounded border px-2"/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/>显示密码</label><p className="mt-3 text-sm text-slate-500">至少 12 个字符。原来的密码无法查看。重设后该同事需重新登录。</p>{error&&<p className="mt-2 text-sm text-red-700">{error}</p>}<div className="mt-4 flex justify-end gap-2"><button disabled={!!busy} type="button" className={button} onClick={()=>setTarget(null)}>取消</button><button disabled={!!busy} className={`${button} bg-teal-700 text-white`}>{busy?"处理中…":"确认重设"}</button></div></form></div>}
 </main>;
}
