import {currentAccount} from "@/app/lib/account-access";
import { getChatGPTUser } from "@/app/chatgpt-auth";
import { database } from "@/db/raw";
import { validQuote, calculateQuote } from "@/app/lib/quotation";
async function dbForQuotes(){const db=database();await db.prepare("CREATE TABLE IF NOT EXISTS quotations (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, owner_name TEXT NOT NULL, data TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)").run();return db;}
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"请先登录"},{status:401});try{const db=await dbForQuotes();const admin=await currentAccount();const result=await (admin?.role==="admin"?db.prepare("SELECT id, owner_name AS ownerName, data, created_at AS createdAt, updated_at AS updatedAt FROM quotations ORDER BY updated_at DESC"):db.prepare("SELECT id, owner_name AS ownerName, data, created_at AS createdAt, updated_at AS updatedAt FROM quotations WHERE owner_id = ? ORDER BY updated_at DESC").bind(user.userId)).all<{id:string;ownerName:string;data:string;createdAt:number;updatedAt:number}>();return Response.json(result.results.map(r=>({...r,data:JSON.parse(r.data)})));}catch(e){console.error(e);return Response.json({error:"报价读取失败"},{status:500});}}
async function save(request:Request,editing:boolean){const user=await getChatGPTUser();if(!user)return Response.json({error:"请先登录"},{status:401});try{const body=await request.json() as {data:unknown;id?:unknown;updatedAt?:unknown};if(!validQuote(body.data))return Response.json({error:"请填写客户、目的港，并检查费用、柜量和汇率"},{status:400});const result=calculateQuote(body.data);if(result.cost<0||result.ocean<0)return Response.json({error:"本地报价不能高于总报价，请调整费用或本地报价拆分"},{status:400});const db=await dbForQuotes(),now=Date.now(),id=editing?body.id:crypto.randomUUID();if(editing){if(typeof id!=="string"||typeof body.updatedAt!=="number")return Response.json({error:"报价编号无效"},{status:400});const updated=await db.prepare("UPDATE quotations SET data = ?, updated_at = ? WHERE id = ? AND owner_id = ? AND updated_at = ?").bind(JSON.stringify(body.data),now,id,user.userId,body.updatedAt).run();if(!updated.meta.changes)return Response.json({error:"报价已变更或不存在，请重新打开报价"},{status:409});}else await db.prepare("INSERT INTO quotations (id, owner_id, owner_name, data, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)").bind(id,user.userId,user.displayName,JSON.stringify(body.data),now,now).run();return Response.json({id,updatedAt:now,createdAt:now,ownerName:user.displayName,data:body.data},{status:editing?200:201});}catch(e){console.error(e);return Response.json({error:"报价保存失败"},{status:500});}}
export async function POST(request:Request){return save(request,false);}
export async function PUT(request:Request){return save(request,true);}
